const Color = {};

// field
Color.FIELD_REGULAR_BACKGROUND = "#E5B300";
Color.FIELD_HOLE_CLOSED_BACKGROUND = "#f00";
Color.FIELD_HOLE_OPENED_BACKGROUND = "#0f0";
Color.FIELD_HOLE_CIRCLES = "#f50"
Color.FIELD_HOT_ZONE_BACKGROUND = "#E5B300";
Color.FIELD_SUPER_HOT_ZONE_BACKGROUND = "#f80";
Color.FIELD_PIT_BACKGROUND = "#444";
Color.FIELD_MIDFIELD_BACKGROUND = "#fe0"

// objects
Color.TORQUE = "#333"
Color.TEAM_1 = "#00f";
Color.TEAM_2 = "#f00";

// UI
Color.FIELD_BORDER_REGULAR = "#915900"
Color.BORDER_HOVER = "#000";
Color.BORDER_SELECT = "#0ff";
Color.BORDER_SELECT_HOVER = "#077";
Color.BORDER_HIGHLIGHT = "#fff";
Color.BORDER_HIGHLIGHT_HOVER = "#777";
Color.GAME_BORDER = "black";
Color.BUTTON = "white";
Color.BUTTON_HOVER = "#77f"
Color.UI_BACKGROUND = "#fff";
Color.BUTTON_BACKGROUND = "#ccc";
Color.BUTTON_BACKGROUND_HOVER = "#fff";
Color.WINDOW_BACKGROUND = "#555";
