const Color = {};

// field
Color.FIELD_REGULAR_BACKGROUND = "#E5B300";
Color.FIELD_HOLE_BACKGROUND = "#f00";
Color.FIELD_HOLE_CIRCLES = "#f50"
Color.FIELD_HOT_ZONE_BACKGROUND = "#E5B300";
Color.FIELD_SUPER_HOT_ZONE_BACKGROUND = "#f80";
Color.FIELD_PIT_BACKGROUND = "#444";
Color.FIELD_MIDFIELD_BACKGROUND = "#fe0"

// objects
Color.BALL = "black"
Color.PLAYER_TEAM_1 = "red";
Color.PLAYER_TEAM_2 = "blue";

// UI
Color.FIELD_BORDER_REGULAR = "#777"
Color.FIELD_BORDER_HOVER = "black";
